#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: fbbd4e3
#
# Source0 file verified with key 0xD7574483BB57B18D (jr@jriddell.org)
#
Name     : kdeplasma-addons
Version  : 6.3.2
Release  : 120
URL      : https://download.kde.org/stable/plasma/6.3.2/kdeplasma-addons-6.3.2.tar.xz
Source0  : https://download.kde.org/stable/plasma/6.3.2/kdeplasma-addons-6.3.2.tar.xz
Source1  : https://download.kde.org/stable/plasma/6.3.2/kdeplasma-addons-6.3.2.tar.xz.sig
Source2  : D7574483BB57B18D.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0 MIT
Requires: kdeplasma-addons-data = %{version}-%{release}
Requires: kdeplasma-addons-lib = %{version}-%{release}
Requires: kdeplasma-addons-license = %{version}-%{release}
Requires: kdeplasma-addons-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : icu4c-dev
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kglobalaccel-dev
BuildRequires : kholidays-dev
BuildRequires : ki18n-dev
BuildRequires : kio-dev
BuildRequires : kirigami-addons-dev
BuildRequires : kjobwidgets-dev
BuildRequires : knotifications-dev
BuildRequires : krunner-dev
BuildRequires : kservice-dev
BuildRequires : plasma5support-dev
BuildRequires : qt6base-dev
BuildRequires : qt6webengine-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Kate Session Runner
========================
This Runner loads a list of Kate's sessions and matches
KRunner's queries against it.

%package data
Summary: data components for the kdeplasma-addons package.
Group: Data

%description data
data components for the kdeplasma-addons package.


%package dev
Summary: dev components for the kdeplasma-addons package.
Group: Development
Requires: kdeplasma-addons-lib = %{version}-%{release}
Requires: kdeplasma-addons-data = %{version}-%{release}
Provides: kdeplasma-addons-devel = %{version}-%{release}
Requires: kdeplasma-addons = %{version}-%{release}

%description dev
dev components for the kdeplasma-addons package.


%package lib
Summary: lib components for the kdeplasma-addons package.
Group: Libraries
Requires: kdeplasma-addons-data = %{version}-%{release}
Requires: kdeplasma-addons-license = %{version}-%{release}

%description lib
lib components for the kdeplasma-addons package.


%package license
Summary: license components for the kdeplasma-addons package.
Group: Default

%description license
license components for the kdeplasma-addons package.


%package locales
Summary: locales components for the kdeplasma-addons package.
Group: Default

%description locales
locales components for the kdeplasma-addons package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) D7574483BB57B18D' gpg.status
%setup -q -n kdeplasma-addons-6.3.2
cd %{_builddir}/kdeplasma-addons-6.3.2
pushd ..
cp -a kdeplasma-addons-6.3.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1741111575
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1741111575
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdeplasma-addons
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/GPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/3c3d7573e137d48253731c975ecf90d74cfa9efe || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/6f1f675aa5f6a2bbaa573b8343044b166be28399 || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kdeplasma-addons-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/kdeplasma-addons/adadb67a9875aeeac285309f1eab6e47d9ee08a7 || :
cp %{_builddir}/kdeplasma-addons-%{version}/kwin/effects/cube/kcm/cubeeffectkcm.ui.license %{buildroot}/usr/share/package-licenses/kdeplasma-addons/f9bb2e988a5b97ddfe98979cd3c3021017f5cbfd || :
cp %{_builddir}/kdeplasma-addons-%{version}/kwin/effects/cube/kcm/resources.qrc.license %{buildroot}/usr/share/package-licenses/kdeplasma-addons/f9bb2e988a5b97ddfe98979cd3c3021017f5cbfd || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang kwin_effect_cube
%find_lang plasma_addons_engine_dict
%find_lang plasma_addons_profiles_utility
%find_lang plasma_applet_org.kde.plasma.addons.katesessions
%find_lang plasma_applet_org.kde.plasma.binaryclock
%find_lang plasma_applet_org.kde.plasma.calculator
%find_lang plasma_applet_org.kde.plasma.colorpicker
%find_lang plasma_applet_org.kde.plasma.comic
%find_lang plasma_applet_org.kde.plasma.diskquota
%find_lang plasma_applet_org.kde.plasma.fifteenpuzzle
%find_lang plasma_applet_org.kde.plasma.fuzzyclock
%find_lang plasma_applet_org.kde.plasma.keyboardindicator
%find_lang plasma_applet_org.kde.plasma.konsoleprofiles
%find_lang plasma_applet_org.kde.plasma.mediaframe
%find_lang plasma_applet_org.kde.plasma.notes
%find_lang plasma_applet_org.kde.plasma.private.grouping
%find_lang plasma_applet_org.kde.plasma.quicklaunch
%find_lang plasma_applet_org.kde.plasma.timer
%find_lang plasma_applet_org.kde.plasma.userswitcher
%find_lang plasma_applet_org.kde.plasma.weather
%find_lang plasma_applet_org.kde.plasma.webbrowser
%find_lang plasma_applet_org.kde.plasma_applet_dict
%find_lang plasma_calendar_alternatecalendar
%find_lang plasma_calendar_astronomicalevents
%find_lang plasma_runner_CharacterRunner
%find_lang plasma_runner_converterrunner
%find_lang plasma_runner_datetime
%find_lang plasma_runner_katesessions
%find_lang plasma_runner_konsoleprofiles
%find_lang plasma_runner_krunner_dictionary
%find_lang plasma_runner_spellcheckrunner
%find_lang plasma_wallpaper_org.kde.potd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/libexec/kf6/kauth/kameleonhelper
/usr/lib64/libexec/kf6/kauth/kameleonhelper

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system-services/org.kde.kameleonhelper.service
/usr/share/dbus-1/system.d/org.kde.kameleonhelper.conf
/usr/share/icons/hicolor/scalable/apps/fifteenpuzzle.svgz
/usr/share/kdevappwizard/templates/plasmapotdprovider.tar.bz2
/usr/share/knotifications6/plasma_applet_timer.notifyrc
/usr/share/knsrcfiles/comic.knsrc
/usr/share/kwin/effects/cube/contents/config/main.xml
/usr/share/kwin/effects/cube/contents/ui/Cube.qml
/usr/share/kwin/effects/cube/contents/ui/CubeCameraController.qml
/usr/share/kwin/effects/cube/contents/ui/CubeFace.qml
/usr/share/kwin/effects/cube/contents/ui/DesktopView.qml
/usr/share/kwin/effects/cube/contents/ui/PlaceholderView.qml
/usr/share/kwin/effects/cube/contents/ui/ScreenView.qml
/usr/share/kwin/effects/cube/contents/ui/constants.js
/usr/share/kwin/effects/cube/contents/ui/main.qml
/usr/share/kwin/effects/cube/metadata.json
/usr/share/kwin/tabbox/big_icons/contents/ui/main.qml
/usr/share/kwin/tabbox/big_icons/metadata.json
/usr/share/kwin/tabbox/compact/contents/ui/main.qml
/usr/share/kwin/tabbox/compact/metadata.json
/usr/share/kwin/tabbox/coverswitch/contents/ui/main.qml
/usr/share/kwin/tabbox/coverswitch/metadata.json
/usr/share/kwin/tabbox/flipswitch/contents/ui/main.qml
/usr/share/kwin/tabbox/flipswitch/metadata.json
/usr/share/kwin/tabbox/sidebar/contents/ui/main.qml
/usr/share/kwin/tabbox/sidebar/metadata.json
/usr/share/metainfo/org.kde.haenau.appdata.xml
/usr/share/metainfo/org.kde.hunyango.appdata.xml
/usr/share/metainfo/org.kde.plasma.addons.katesessions.appdata.xml
/usr/share/metainfo/org.kde.plasma.binaryclock.appdata.xml
/usr/share/metainfo/org.kde.plasma.calculator.appdata.xml
/usr/share/metainfo/org.kde.plasma.colorpicker.appdata.xml
/usr/share/metainfo/org.kde.plasma.comic.appdata.xml
/usr/share/metainfo/org.kde.plasma.diskquota.appdata.xml
/usr/share/metainfo/org.kde.plasma.fifteenpuzzle.appdata.xml
/usr/share/metainfo/org.kde.plasma.fuzzyclock.appdata.xml
/usr/share/metainfo/org.kde.plasma.grouping.appdata.xml
/usr/share/metainfo/org.kde.plasma.keyboardindicator.appdata.xml
/usr/share/metainfo/org.kde.plasma.kickerdash.appdata.xml
/usr/share/metainfo/org.kde.plasma.konsoleprofiles.appdata.xml
/usr/share/metainfo/org.kde.plasma.mediaframe.appdata.xml
/usr/share/metainfo/org.kde.plasma.notes.appdata.xml
/usr/share/metainfo/org.kde.plasma.quicklaunch.appdata.xml
/usr/share/metainfo/org.kde.plasma.timer.appdata.xml
/usr/share/metainfo/org.kde.plasma.userswitcher.appdata.xml
/usr/share/metainfo/org.kde.plasma.weather.appdata.xml
/usr/share/metainfo/org.kde.potd.appdata.xml
/usr/share/plasma/desktoptheme/default/weather/wind-arrows.svgz
/usr/share/plasma/desktoptheme/default/widgets/timer.svgz
/usr/share/plasma/plasmoids/org.kde.plasma.addons.katesessions/contents/ui/KateSessionsItemDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.addons.katesessions/contents/ui/Menu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.addons.katesessions/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.addons.katesessions/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.binaryclock/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.binaryclock/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.binaryclock/contents/ui/BinaryClock.qml
/usr/share/plasma/plasmoids/org.kde.plasma.binaryclock/contents/ui/configGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.binaryclock/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.binaryclock/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.calculator/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.calculator/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.colorpicker/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.colorpicker/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.colorpicker/contents/ui/ColorCircle.qml
/usr/share/plasma/plasmoids/org.kde.plasma.colorpicker/contents/ui/ColorContextMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.colorpicker/contents/ui/CompactRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.colorpicker/contents/ui/ImageColors.qml
/usr/share/plasma/plasmoids/org.kde.plasma.colorpicker/contents/ui/LoadingIndicator.qml
/usr/share/plasma/plasmoids/org.kde.plasma.colorpicker/contents/ui/configGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.colorpicker/contents/ui/logic.js
/usr/share/plasma/plasmoids/org.kde.plasma.colorpicker/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.colorpicker/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.comic/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.comic/contents/ui/ButtonBar.qml
/usr/share/plasma/plasmoids/org.kde.plasma.comic/contents/ui/ComicBottomInfo.qml
/usr/share/plasma/plasmoids/org.kde.plasma.comic/contents/ui/ComicCentralView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.comic/contents/ui/FullViewWidget.qml
/usr/share/plasma/plasmoids/org.kde.plasma.comic/contents/ui/ImageWidget.qml
/usr/share/plasma/plasmoids/org.kde.plasma.comic/contents/ui/configAdvanced.qml
/usr/share/plasma/plasmoids/org.kde.plasma.comic/contents/ui/configAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.comic/contents/ui/configGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.comic/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.comic/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.diskquota/contents/ui/ListDelegateItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.diskquota/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.diskquota/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.fifteenpuzzle/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.fifteenpuzzle/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.fifteenpuzzle/contents/ui/FifteenPuzzle.qml
/usr/share/plasma/plasmoids/org.kde.plasma.fifteenpuzzle/contents/ui/Piece.qml
/usr/share/plasma/plasmoids/org.kde.plasma.fifteenpuzzle/contents/ui/blanksquare.svg
/usr/share/plasma/plasmoids/org.kde.plasma.fifteenpuzzle/contents/ui/configAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.fifteenpuzzle/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.fifteenpuzzle/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.fuzzyclock/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.fuzzyclock/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.fuzzyclock/contents/ui/FuzzyClock.qml
/usr/share/plasma/plasmoids/org.kde.plasma.fuzzyclock/contents/ui/configAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.fuzzyclock/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.fuzzyclock/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.grouping/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.grouping/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.keyboardindicator/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.keyboardindicator/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.keyboardindicator/contents/ui/configAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.keyboardindicator/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.keyboardindicator/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.kickerdash/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.konsoleprofiles/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.konsoleprofiles/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.mediaframe/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.mediaframe/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.mediaframe/contents/ui/ConfigGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.mediaframe/contents/ui/ConfigPaths.qml
/usr/share/plasma/plasmoids/org.kde.plasma.mediaframe/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.mediaframe/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/ShortcutMenuItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/configAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.notes/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.private.grouping/contents/applet/CompactApplet.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.grouping/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.grouping/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.private.grouping/contents/ui/items/AbstractItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.grouping/contents/ui/items/PlasmoidItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.grouping/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.private.grouping/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.quicklaunch/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.quicklaunch/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.quicklaunch/contents/ui/ConfigGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.quicklaunch/contents/ui/IconItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.quicklaunch/contents/ui/Popup.qml
/usr/share/plasma/plasmoids/org.kde.plasma.quicklaunch/contents/ui/UrlModel.qml
/usr/share/plasma/plasmoids/org.kde.plasma.quicklaunch/contents/ui/layout.js
/usr/share/plasma/plasmoids/org.kde.plasma.quicklaunch/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.quicklaunch/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.timer/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.timer/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.timer/contents/ui/CompactRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.timer/contents/ui/TimerEdit.qml
/usr/share/plasma/plasmoids/org.kde.plasma.timer/contents/ui/TimerView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.timer/contents/ui/configAdvanced.qml
/usr/share/plasma/plasmoids/org.kde.plasma.timer/contents/ui/configAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.timer/contents/ui/configTimes.qml
/usr/share/plasma/plasmoids/org.kde.plasma.timer/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.timer/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.userswitcher/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.userswitcher/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.userswitcher/contents/ui/ActionListDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.userswitcher/contents/ui/ListDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.userswitcher/contents/ui/UserListDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.userswitcher/contents/ui/configGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.userswitcher/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.userswitcher/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/CompactRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/DetailsView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/ForecastView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/FullRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/IconAndTextItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/NoticesView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/SwitchPanel.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/TopPanel.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/config/ConfigAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/config/ConfigUnits.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/config/ConfigWeatherStation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.weather/metadata.json
/usr/share/plasma/wallpapers/org.kde.haenau/contents/ui/BackgroundElement.qml
/usr/share/plasma/wallpapers/org.kde.haenau/contents/ui/BottomBackgroundElement.qml
/usr/share/plasma/wallpapers/org.kde.haenau/contents/ui/RightBackgroundElement.qml
/usr/share/plasma/wallpapers/org.kde.haenau/contents/ui/main.qml
/usr/share/plasma/wallpapers/org.kde.haenau/contents/ui/wallpaper.svgz
/usr/share/plasma/wallpapers/org.kde.haenau/metadata.json
/usr/share/plasma/wallpapers/org.kde.hunyango/contents/ui/ColorProvider.qml
/usr/share/plasma/wallpapers/org.kde.hunyango/contents/ui/main.qml
/usr/share/plasma/wallpapers/org.kde.hunyango/contents/ui/qmldir
/usr/share/plasma/wallpapers/org.kde.hunyango/contents/ui/wallpaper.svgz
/usr/share/plasma/wallpapers/org.kde.hunyango/metadata.json
/usr/share/plasma/wallpapers/org.kde.potd/contents/config/main.xml
/usr/share/plasma/wallpapers/org.kde.potd/contents/ui/ActionContextMenu.qml
/usr/share/plasma/wallpapers/org.kde.potd/contents/ui/WallpaperDelegate.qml
/usr/share/plasma/wallpapers/org.kde.potd/contents/ui/WallpaperPreview.qml
/usr/share/plasma/wallpapers/org.kde.potd/contents/ui/config.qml
/usr/share/plasma/wallpapers/org.kde.potd/contents/ui/main.qml
/usr/share/plasma/wallpapers/org.kde.potd/metadata.json
/usr/share/polkit-1/actions/org.kde.kameleonhelper.policy
/usr/share/qlogging-categories6/kdeplasma-addons.categories

%files dev
%defattr(-,root,root,-)
/usr/include/plasma/potdprovider/plasma_potd_export.h
/usr/include/plasma/potdprovider/potdprovider.h
/usr/lib64/cmake/PlasmaPotdProvider/PlasmaPotdProviderConfig.cmake
/usr/lib64/cmake/PlasmaPotdProvider/PlasmaPotdProviderConfigVersion.cmake
/usr/lib64/cmake/PlasmaPotdProvider/PlasmaPotdProviderTargets-relwithdebinfo.cmake
/usr/lib64/cmake/PlasmaPotdProvider/PlasmaPotdProviderTargets.cmake
/usr/lib64/libplasmapotdprovidercore.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libplasmapotdprovidercore.so.2.0.0
/V3/usr/lib64/qt6/plugins/kf6/kded/kameleon.so
/V3/usr/lib64/qt6/plugins/kf6/krunner/kcms/kcm_krunner_charrunner.so
/V3/usr/lib64/qt6/plugins/kf6/krunner/kcms/kcm_krunner_dictionary.so
/V3/usr/lib64/qt6/plugins/kf6/krunner/kcms/kcm_krunner_spellcheck.so
/V3/usr/lib64/qt6/plugins/kf6/krunner/krunner_charrunner.so
/V3/usr/lib64/qt6/plugins/kf6/krunner/krunner_dictionary.so
/V3/usr/lib64/qt6/plugins/kf6/krunner/krunner_katesessions.so
/V3/usr/lib64/qt6/plugins/kf6/krunner/krunner_konsoleprofiles.so
/V3/usr/lib64/qt6/plugins/kf6/krunner/krunner_spellcheck.so
/V3/usr/lib64/qt6/plugins/kf6/krunner/org.kde.datetime.so
/V3/usr/lib64/qt6/plugins/kf6/krunner/unitconverter.so
/V3/usr/lib64/qt6/plugins/kf6/packagestructure/plasma_comic.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_cube_config.so
/V3/usr/lib64/qt6/plugins/plasma/applets/org.kde.plasma.comic.so
/V3/usr/lib64/qt6/plugins/plasma/applets/org.kde.plasma.grouping.so
/V3/usr/lib64/qt6/plugins/plasma/applets/org.kde.plasma.private.grouping.so
/V3/usr/lib64/qt6/plugins/plasma/applets/org.kde.plasma.weather.so
/V3/usr/lib64/qt6/plugins/plasmacalendarplugins/alternatecalendar.so
/V3/usr/lib64/qt6/plugins/plasmacalendarplugins/astronomicalevents.so
/V3/usr/lib64/qt6/plugins/potd/plasma_potd_apodprovider.so
/V3/usr/lib64/qt6/plugins/potd/plasma_potd_bingprovider.so
/V3/usr/lib64/qt6/plugins/potd/plasma_potd_epodprovider.so
/V3/usr/lib64/qt6/plugins/potd/plasma_potd_flickrprovider.so
/V3/usr/lib64/qt6/plugins/potd/plasma_potd_noaaprovider.so
/V3/usr/lib64/qt6/plugins/potd/plasma_potd_simonstalenhagprovider.so
/V3/usr/lib64/qt6/plugins/potd/plasma_potd_wcpotdprovider.so
/V3/usr/lib64/qt6/qml/org/kde/plasma/private/alternatecalendarconfig/libplasmacalendaralternatecalendarconfig.so
/V3/usr/lib64/qt6/qml/org/kde/plasma/private/colorpicker/libcolorpickerplugin.so
/V3/usr/lib64/qt6/qml/org/kde/plasma/private/diskquota/libdiskquotaplugin.so
/V3/usr/lib64/qt6/qml/org/kde/plasma/private/fifteenpuzzle/libfifteenpuzzleplugin.so
/V3/usr/lib64/qt6/qml/org/kde/plasma/private/mediaframe/libmediaframeplugin.so
/V3/usr/lib64/qt6/qml/org/kde/plasma/private/notes/libnotesplugin.so
/V3/usr/lib64/qt6/qml/org/kde/plasma/private/profiles/libprofiles_qml_plugin.so
/V3/usr/lib64/qt6/qml/org/kde/plasma/private/quicklaunch/libquicklaunchplugin.so
/V3/usr/lib64/qt6/qml/org/kde/plasma/private/timer/libtimerplugin.so
/V3/usr/lib64/qt6/qml/org/kde/plasma/private/weather/libweatherplugin.so
/V3/usr/lib64/qt6/qml/org/kde/plasma/wallpapers/potd/libplasma_wallpaper_potdplugin.so
/V3/usr/lib64/qt6/qml/org/kde/plasmacalendar/astronomicaleventsconfig/libplasmacalendarastronomicaleventsconfig.so
/usr/lib64/libplasmapotdprovidercore.so.2
/usr/lib64/libplasmapotdprovidercore.so.2.0.0
/usr/lib64/qt6/plugins/kf6/kded/kameleon.so
/usr/lib64/qt6/plugins/kf6/krunner/kcms/kcm_krunner_charrunner.so
/usr/lib64/qt6/plugins/kf6/krunner/kcms/kcm_krunner_dictionary.so
/usr/lib64/qt6/plugins/kf6/krunner/kcms/kcm_krunner_spellcheck.so
/usr/lib64/qt6/plugins/kf6/krunner/krunner_charrunner.so
/usr/lib64/qt6/plugins/kf6/krunner/krunner_dictionary.so
/usr/lib64/qt6/plugins/kf6/krunner/krunner_katesessions.so
/usr/lib64/qt6/plugins/kf6/krunner/krunner_konsoleprofiles.so
/usr/lib64/qt6/plugins/kf6/krunner/krunner_spellcheck.so
/usr/lib64/qt6/plugins/kf6/krunner/org.kde.datetime.so
/usr/lib64/qt6/plugins/kf6/krunner/unitconverter.so
/usr/lib64/qt6/plugins/kf6/packagestructure/plasma_comic.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_cube_config.so
/usr/lib64/qt6/plugins/plasma/applets/org.kde.plasma.comic.so
/usr/lib64/qt6/plugins/plasma/applets/org.kde.plasma.grouping.so
/usr/lib64/qt6/plugins/plasma/applets/org.kde.plasma.private.grouping.so
/usr/lib64/qt6/plugins/plasma/applets/org.kde.plasma.weather.so
/usr/lib64/qt6/plugins/plasmacalendarplugins/alternatecalendar.so
/usr/lib64/qt6/plugins/plasmacalendarplugins/alternatecalendar/AlternateCalendarConfig.qml
/usr/lib64/qt6/plugins/plasmacalendarplugins/astronomicalevents.so
/usr/lib64/qt6/plugins/plasmacalendarplugins/astronomicalevents/AstronomicalEventsConfig.qml
/usr/lib64/qt6/plugins/potd/plasma_potd_apodprovider.so
/usr/lib64/qt6/plugins/potd/plasma_potd_bingprovider.so
/usr/lib64/qt6/plugins/potd/plasma_potd_epodprovider.so
/usr/lib64/qt6/plugins/potd/plasma_potd_flickrprovider.so
/usr/lib64/qt6/plugins/potd/plasma_potd_noaaprovider.so
/usr/lib64/qt6/plugins/potd/plasma_potd_simonstalenhagprovider.so
/usr/lib64/qt6/plugins/potd/plasma_potd_wcpotdprovider.so
/usr/lib64/qt6/qml/org/kde/plasma/private/alternatecalendarconfig/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/private/alternatecalendarconfig/libplasmacalendaralternatecalendarconfig.so
/usr/lib64/qt6/qml/org/kde/plasma/private/alternatecalendarconfig/plasmacalendaralternatecalendarconfig.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/private/alternatecalendarconfig/qmldir
/usr/lib64/qt6/qml/org/kde/plasma/private/colorpicker/colorpickerplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/private/colorpicker/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/private/colorpicker/libcolorpickerplugin.so
/usr/lib64/qt6/qml/org/kde/plasma/private/colorpicker/qmldir
/usr/lib64/qt6/qml/org/kde/plasma/private/diskquota/diskquotaplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/private/diskquota/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/private/diskquota/libdiskquotaplugin.so
/usr/lib64/qt6/qml/org/kde/plasma/private/diskquota/qmldir
/usr/lib64/qt6/qml/org/kde/plasma/private/fifteenpuzzle/fifteenpuzzleplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/private/fifteenpuzzle/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/private/fifteenpuzzle/libfifteenpuzzleplugin.so
/usr/lib64/qt6/qml/org/kde/plasma/private/fifteenpuzzle/qmldir
/usr/lib64/qt6/qml/org/kde/plasma/private/mediaframe/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/private/mediaframe/libmediaframeplugin.so
/usr/lib64/qt6/qml/org/kde/plasma/private/mediaframe/mediaframeplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/private/mediaframe/qmldir
/usr/lib64/qt6/qml/org/kde/plasma/private/notes/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/private/notes/libnotesplugin.so
/usr/lib64/qt6/qml/org/kde/plasma/private/notes/notesplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/private/notes/qmldir
/usr/lib64/qt6/qml/org/kde/plasma/private/profiles/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/private/profiles/libprofiles_qml_plugin.so
/usr/lib64/qt6/qml/org/kde/plasma/private/profiles/profiles_qml_plugin.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/private/profiles/qmldir
/usr/lib64/qt6/qml/org/kde/plasma/private/quicklaunch/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/private/quicklaunch/libquicklaunchplugin.so
/usr/lib64/qt6/qml/org/kde/plasma/private/quicklaunch/qmldir
/usr/lib64/qt6/qml/org/kde/plasma/private/quicklaunch/quicklaunchplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/private/timer/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/private/timer/libtimerplugin.so
/usr/lib64/qt6/qml/org/kde/plasma/private/timer/qmldir
/usr/lib64/qt6/qml/org/kde/plasma/private/timer/timerplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/private/weather/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/private/weather/libweatherplugin.so
/usr/lib64/qt6/qml/org/kde/plasma/private/weather/qmldir
/usr/lib64/qt6/qml/org/kde/plasma/private/weather/weatherplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/wallpapers/potd/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/wallpapers/potd/libplasma_wallpaper_potdplugin.so
/usr/lib64/qt6/qml/org/kde/plasma/wallpapers/potd/plasma_wallpaper_potdplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/wallpapers/potd/qmldir
/usr/lib64/qt6/qml/org/kde/plasmacalendar/astronomicaleventsconfig/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasmacalendar/astronomicaleventsconfig/libplasmacalendarastronomicaleventsconfig.so
/usr/lib64/qt6/qml/org/kde/plasmacalendar/astronomicaleventsconfig/plasmacalendarastronomicaleventsconfig.qmltypes
/usr/lib64/qt6/qml/org/kde/plasmacalendar/astronomicaleventsconfig/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdeplasma-addons/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/kdeplasma-addons/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/kdeplasma-addons/3c3d7573e137d48253731c975ecf90d74cfa9efe
/usr/share/package-licenses/kdeplasma-addons/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/kdeplasma-addons/6f1f675aa5f6a2bbaa573b8343044b166be28399
/usr/share/package-licenses/kdeplasma-addons/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/kdeplasma-addons/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/kdeplasma-addons/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/kdeplasma-addons/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/kdeplasma-addons/adadb67a9875aeeac285309f1eab6e47d9ee08a7
/usr/share/package-licenses/kdeplasma-addons/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/kdeplasma-addons/e712eadfab0d2357c0f50f599ef35ee0d87534cb
/usr/share/package-licenses/kdeplasma-addons/f9bb2e988a5b97ddfe98979cd3c3021017f5cbfd

%files locales -f kwin_effect_cube.lang -f plasma_addons_engine_dict.lang -f plasma_addons_profiles_utility.lang -f plasma_applet_org.kde.plasma.addons.katesessions.lang -f plasma_applet_org.kde.plasma.binaryclock.lang -f plasma_applet_org.kde.plasma.calculator.lang -f plasma_applet_org.kde.plasma.colorpicker.lang -f plasma_applet_org.kde.plasma.comic.lang -f plasma_applet_org.kde.plasma.diskquota.lang -f plasma_applet_org.kde.plasma.fifteenpuzzle.lang -f plasma_applet_org.kde.plasma.fuzzyclock.lang -f plasma_applet_org.kde.plasma.keyboardindicator.lang -f plasma_applet_org.kde.plasma.konsoleprofiles.lang -f plasma_applet_org.kde.plasma.mediaframe.lang -f plasma_applet_org.kde.plasma.notes.lang -f plasma_applet_org.kde.plasma.private.grouping.lang -f plasma_applet_org.kde.plasma.quicklaunch.lang -f plasma_applet_org.kde.plasma.timer.lang -f plasma_applet_org.kde.plasma.userswitcher.lang -f plasma_applet_org.kde.plasma.weather.lang -f plasma_applet_org.kde.plasma.webbrowser.lang -f plasma_applet_org.kde.plasma_applet_dict.lang -f plasma_calendar_alternatecalendar.lang -f plasma_calendar_astronomicalevents.lang -f plasma_runner_CharacterRunner.lang -f plasma_runner_converterrunner.lang -f plasma_runner_datetime.lang -f plasma_runner_katesessions.lang -f plasma_runner_konsoleprofiles.lang -f plasma_runner_krunner_dictionary.lang -f plasma_runner_spellcheckrunner.lang -f plasma_wallpaper_org.kde.potd.lang
%defattr(-,root,root,-)

